steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/optify-core-engine:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/optify-core-engine:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'optify-core-engine'
    - '--image'
    - 'gcr.io/$PROJECT_ID/optify-core-engine:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'NODE_ENV=production,PORT=8080'
    - '--set-secrets'
    - 'FIREBASE_PRIVATE_KEY=firebase-private-key:latest,MERCADO_PAGO_ACCESS_TOKEN=mercado-pago-token:latest'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/optify-core-engine:$COMMIT_SHA'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY








