// Barrel exports para ícones - otimização de bundle
export { 
  LayoutDashboard, 
  Users, 
  DollarSign, 
  FileText, 
  Calendar, 
  Settings, 
  LogOut,
  PieChart,
  TrendingUp,
  Shield,
  UserCircle,
  Gift,
  Clock,
  Crown,
  Menu,
  X,
  Home,
  ArrowRight,
  Check,
  AlertTriangle,
  Loader2,
  Plus,
  Edit,
  Trash2,
  Eye,
  Search,
  Filter,
  Download,
  Upload,
  Copy,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Star,
  Heart,
  Share2,
  MessageCircle,
  Bell,
  Mail,
  Phone,
  MapPin,
  Globe,
  Lock,
  Unlock,
  Key,
  CreditCard,
  Wallet,
  ShoppingCart,
  Package,
  Truck,
  Building,
  Briefcase,
  GraduationCap,
  Award,
  Target,
  Zap,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  Wind,
  Thermometer,
  Droplets,
  Umbrella,
  TreePine,
  Flower,
  Leaf,
  Bug,
  Fish,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Coffee,
  Pizza,
  Cake,
  Apple,
  Banana,
  Carrot,
  Grape,
  Lemon,
  Orange,
  Strawberry,
  Cherry,
  IceCream,
  Cookie,
  Beer,
  Wine,
  Cocktail,
  Coffee as CoffeeIcon,
  Camera,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  Volume2,
  Play,
  Pause,
  Stop,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  RefreshCw,
  RefreshCcw,
  Undo,
  Redo,
  Save,
  Bookmark,
  BookmarkCheck,
  Flag,
  Tag,
  Hash,
  AtSign,
  Percent,
  DollarSign as DollarIcon,
  Euro,
  Pound,
  Yen,
  Bitcoin,
  CreditCard as CardIcon,
  Receipt,
  Calculator,
  TrendingUp as TrendingUpIcon,
  TrendingDown,
  BarChart3,
  LineChart,
  Activity,
  Zap as ZapIcon,
  Battery,
  BatteryLow,
  BatteryMedium,
  BatteryFull,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothOff,
  Signal,
  SignalLow,
  SignalMedium,
  SignalHigh,
  SignalZero,
  Radio,
  Tv,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Watch,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Printer,
  Scanner,
  HardDrive,
  Database,
  Server,
  Router,
  Modem,
  Cpu,
  Memory,
  HardDrive as HDDIcon,
  Disc,
  CD,
  DVD,
  USB,
  HDMI,
  Ethernet,
  Power,
  PowerOff,
  PlayCircle,
  PauseCircle,
  StopCircle,
  SkipBackCircle,
  SkipForwardCircle,
  RepeatCircle,
  ShuffleCircle,
  VolumeX,
  Volume1,
  Volume2 as Volume2Icon,
  Mic as MicIcon,
  MicOff,
  Headphones as HeadphonesIcon,
  HeadphonesOff,
  Radio as RadioIcon,
  Tv as TvIcon,
  Monitor as MonitorIcon,
  Laptop as LaptopIcon,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Watch as WatchIcon,
  Gamepad2 as GamepadIcon,
  Joystick as JoystickIcon,
  Keyboard as KeyboardIcon,
  Mouse as MouseIcon,
  Printer as PrinterIcon,
  Scanner as ScannerIcon,
  HardDrive as HardDriveIcon,
  Database as DatabaseIcon,
  Server as ServerIcon,
  Router as RouterIcon,
  Modem as ModemIcon,
  Cpu as CpuIcon,
  Memory as MemoryIcon,
  Disc as DiscIcon,
  CD as CDIcon,
  DVD as DVDIcon,
  USB as USBIcon,
  HDMI as HDMIIcon,
  Ethernet as EthernetIcon,
  Power as PowerIcon,
  PowerOff as PowerOffIcon
} from 'lucide-react';

// Re-export commonly used icons with shorter names
export { LayoutDashboard as Dashboard } from 'lucide-react';
export { Users as UsersIcon } from 'lucide-react';
export { DollarSign as Money } from 'lucide-react';
export { FileText as File } from 'lucide-react';
export { Calendar as CalendarIcon } from 'lucide-react';
export { Settings as SettingsIcon } from 'lucide-react';
export { LogOut as Logout } from 'lucide-react';
export { PieChart as Chart } from 'lucide-react';
export { TrendingUp as Trending } from 'lucide-react';
export { Shield as Security } from 'lucide-react';
export { UserCircle as User } from 'lucide-react';
export { Gift as GiftIcon } from 'lucide-react';
export { Clock as Time } from 'lucide-react';
export { Crown as Premium } from 'lucide-react';
